### ISSUE TITLE
Need help to connect any particular device

### ISSUE THREAD

**Issue by utpalruparel** [itsJoKr/LocalNetwork#2]
Hello,

I am using this library for one of my project. I want to know how will I able to discover and list all the device which to connect?
Guide to it will help me to fix my problem.

Thanks

**Comment by itsJoKr** [comment]
I was investigating this with several devices and networks.

Unfortunately, UDP broadcasts are not guaranteed to work on all networks/routers/phones. That's why I'm deprecating this. You can still manually type server IP to connect devices and then communicate with TCP sockets, but you don't need this lib in that case.
